In [ ]:
# 1) Imports
import json
import pandas as pd
from pathlib import Path

In [ ]:
# DATASET INFO_LOTES

In [ ]:
# 2) Ruta
ruta = Path("..") / "dataset" / "info_lote.json"

# Verificación
print("Existe archivo?:", ruta.exists(), "| Ruta:", ruta)

# 3) Leer el JSON
with open(ruta, "r", encoding="utf-8") as f:
    data = json.load(f)

print("Tipo dato:", type(data))

rows = []
for lote, lista in data.items():
    for item in lista:
        item["lote"] = lote  # añadimos la clave como nueva columna
        rows.append(item)


info_lotes = pd.DataFrame(rows)
info_lotes.head(1)

Existe archivo?: True | Ruta: ..\dataset\info_lote.json
Tipo dato: <class 'dict'>

          t_id          marca  coste_inicial             lote
0  Apple 1.png  ParaísoFrutal       2.642048  G80V76K49J80T71

In [ ]:
# DATASET LOTES

In [2]:
# 2) Ruta
ruta_2 = Path("..") / "dataset" / "lotes.json"

# Verificación
print("Existe archivo?:", ruta_2.exists(), "| Ruta:", ruta_2)

# 3) Leer el JSON
with open(ruta_2, "r", encoding="utf-8") as f:
    data_2 = json.load(f)

print("Tipo dato:", type(data_2))

lotes= pd.DataFrame(list(data_2.items()), columns=["t_id", "lote"])
lotes.head(1)

NameError: name 'Path' is not defined

In [1]:
from google.colab import files
# Supongamos que tu dataset es un dataframe llamado 'df'
df.to_csv('mi_dataset.csv', index=False)
files.download('mi_dataset.csv')

NameError: name 'df' is not defined

In [ ]:
# DATASET PROVEEDORES

In [ ]:
# 2) Ruta
ruta_3 = Path("..") / "dataset" / "proveedores.json"

# Verificación
print("Existe archivo?:", ruta_3.exists(), "| Ruta:", ruta_3)

# 3) Leer el JSON
with open(ruta_3, "r", encoding="utf-8") as f:
    data_3 = json.load(f)

print("Tipo dato:", type(data_3))

# Creamos una lista con las columnas que necesitamos en el DF
rows_3 = []
for proveedor, lista in data_3.items():
    for item in lista:
        item["proveedor"] = proveedor  # añadimos la clave como nueva columna
        rows_3.append(item)


proveedores = pd.DataFrame(rows_3)
proveedores.head(1)

Existe archivo?: True | Ruta: ..\dataset\proveedores.json
Tipo dato: <class 'dict'>

          t_id                             proveedor
0  Apple 1.png  Agricultura Inteligente TechCultivos

In [ ]:
# DATASET PROVEEDORES-CLIENTES

In [ ]:
# 2) Ruta
ruta_4 = Path("..") / "dataset" / "proveedores-clientes.json"

# Verificación
print("Existe archivo?:", ruta_4.exists(), "| Ruta:", ruta_4)

# 3) Leer el JSON
with open(ruta_4, "r", encoding="utf-8") as f:
    data_4 = json.load(f)

print("Tipo dato:", type(data_4))

# Creamos una lista para los nombres de las columnas del DF
rows_4 = []

for proveedor, lista in data_4.items():
    for item in lista:
        # item = ["image12.png", "CompraMaestra"] ejemplo de lógica al indexar
        t_id = item[0] if len(item) > 0 else None
        cliente = item[1] if len(item) > 1 else None

        rows_4.append({
            "proveedor": proveedor,
            "t_id": t_id,
            "cliente": cliente
        })


proveedores_clientes = pd.DataFrame(rows_4)
proveedores_clientes.head(1)

Existe archivo?: True | Ruta: ..\dataset\proveedores-clientes.json
Tipo dato: <class 'dict'>

                              proveedor         t_id        cliente
0  Agricultura Inteligente TechCultivos  Apple 1.png  CompraMaestra

In [ ]:
# DATASET TIPO

In [ ]:
# 2) Ruta
ruta_5 = Path("..") / "dataset" / "tipo.json"

# Verificación
print("Existe archivo?:", ruta_5.exists(), "| Ruta:", ruta_5)

# 3) Leer el JSON
with open(ruta_5, "r", encoding="utf-8") as f:
    data_5 = json.load(f)

print("Tipo dato:", type(data_5))

# Creamos una lista con las columnas que necesitamos en el DF
rows_5 = []
for tipo, lista in data_5.items():
    for item in lista:
        item["tipo"] = tipo  # añadimos la clave como nueva columna
        rows_5.append(item)


tipo = pd.DataFrame(rows_5)
tipo.head(1)

Existe archivo?: True | Ruta: ..\dataset\tipo.json
Tipo dato: <class 'dict'>

          t_id   tipo  tiempo_recogida
0  Apple 1.png  Apple              433

In [ ]:
# DATASET VENTA EN CLIENTE

In [ ]:
# 2) Ruta
ruta_6 = Path("..") / "dataset" / "venta_en_cliente.json"

# Verificación
print("Existe archivo?:", ruta_6.exists(), "| Ruta:", ruta_6)

# 3) Leer el JSON
with open(ruta_6, "r", encoding="utf-8") as f:
    data_6 = json.load(f)

print("Tipo dato:", type(data_6))

# Creamos una lista con las columnas para el DF
rows_6 = []
for cliente, lista in data_6.items():
    for item in lista:
        item["cliente"] = cliente  # añadimos la clave como nueva columna
        rows_6.append(item)


venta_en_cliente = pd.DataFrame(rows_6)
venta_en_cliente.head(1)

Existe archivo?: True | Ruta: ..\dataset\venta_en_cliente.json
Tipo dato: <class 'dict'>

          t_id  tiempo_venta  precio_venta        peso        cliente
0  Apple 1.png         437.0       4.90968  264.195357  CompraMaestra